###########
#
# sqlmigrate設定ファイル
#
###########
development:
    dialect: postgres
    dir: ./migrations
    table: migration
    datasource: host=${DB_HOST} port=${DB_PORT} dbname=${DB_NAME} user=${DB_USER} password=${DB_PASSWORD} sslmode=disable
