###########
#
# sqlmigrate設定ファイル
#
###########
development:
    dialect: postgres
    dir: ./migrations
    table: migration
    datasource: host=localhost port=5432 dbname=stackies_dev user=postgres password=postgres sslmode=disable
