// Code generated by MockGen. DO NOT EDIT.
// Source: experience_repository.go

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"
	model "stackies/backend/infra/repository/model"

	gomock "github.com/golang/mock/gomock"
)

// MockExperienceRepository is a mock of ExperienceRepository interface.
type MockExperienceRepository struct {
	ctrl     *gomock.Controller
	recorder *MockExperienceRepositoryMockRecorder
}

// MockExperienceRepositoryMockRecorder is the mock recorder for MockExperienceRepository.
type MockExperienceRepositoryMockRecorder struct {
	mock *MockExperienceRepository
}

// NewMockExperienceRepository creates a new mock instance.
func NewMockExperienceRepository(ctrl *gomock.Controller) *MockExperienceRepository {
	mock := &MockExperienceRepository{ctrl: ctrl}
	mock.recorder = &MockExperienceRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExperienceRepository) EXPECT() *MockExperienceRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockExperienceRepository) Create(experience model.Experience) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", experience)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockExperienceRepositoryMockRecorder) Create(experience interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockExperienceRepository)(nil).Create), experience)
}

// GetAll mocks base method.
func (m *MockExperienceRepository) GetAll() ([]model.Experience, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll")
	ret0, _ := ret[0].([]model.Experience)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockExperienceRepositoryMockRecorder) GetAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockExperienceRepository)(nil).GetAll))
}
